### ISSUE TITLE
zarkk01 - Staked `GAMMA` amounts are distributed as rewards leading to users unable to withdraw

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-gamma-staking-judging#109]
zarkk01

high

# Staked `GAMMA` amounts are distributed as rewards leading to users unable to withdraw

## Summary
Staked `GAMMA` tokens will be counted as `unseenRewards` and will be distributed to every participant leading to protocol's accounting mechanisms to break and users unable to withdraw their staked funds

## Vulnerability Detail
First of all, according to team's statements, they have the intention to use `GAMMA` token as both `stakingToken` and also one of the `rewardTokens` together with WETH.

<details>
<summary> Statements </summary>
<img width="612" alt="Screenshot 2024-05-20 at 08 25 36" src="https://github.com/sherlock-audit/2024-05-gamma-staking-zarkk01/assets/77061323/d930ed4b-0b89-4211-b6b4-63b1b7e69a24">
<img width="613" alt="Screenshot 2024-05-20 at 08 23 45" src="https://github.com/sherlock-audit/2024-05-gamma-staking-zarkk01/assets/77061323/69f0c677-c2ca-4601-94e2-e990f37c123f">
<img width="813" alt="Screenshot 2024-05-20 at 08 23 11" src="https://github.com/sherlock-audit/2024-05-gamma-staking-zarkk01/assets/77061323/2948837f-7b33-45ad-8630-12c54ae0ff60">
</details>

At first glance, this seems impossible due to [this](https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L175) check on `addReward` function but this can easily be bypassed if they just add the rewards first and then set the staking token.  The bug has to do with the fact that when the rewards are counted by calling the `notifyUnseenReward()` the `GAMMA` balance of the `Lock` contract will contain both the staked amounts and the amounts that are indeed for distribution purposes. However, the functions logic(as shown in the Code Snippet) does not check for this and assumes that whatever `GAMMA` is "inside" the contract is about to be distributed as reward. This, of course, will break the protocol's accounting and will have as result all of the `GAMMA` tokens to be given as reward. As a result, stakers will not be able to withdraw their funds since they are distributed.  But, even if some stakers withdraw their `GAMMA` that means that other users will not receive their rewards. To understand better the bug, add this test suite in `test` file and run `forge test --mt testFunctionality` :

```solidity
pragma solidity 0.8.23;

import {Test, console} from "forge-std/Test.sol";
import "../src/Lock.sol";
import "../src/mock/MockToken.sol";
import "../src/libraries/LockList.sol";

contract PoC is Test {
    Lock lock;
    LockList lockList;
    address deployer;
    address user1;
    address user2;
    address user3;
    MockToken _stakingToken;
    MockToken _rewardToken;
    uint256[] lockPeriod;
    uint256[] lockMultiplier;
    address[] rewardTokens;

    function setUp() public {
        user1 = vm.addr(1);
        user2 = vm.addr(2);
        user3 = vm.addr(3);
        deployer = vm.addr(9999999);
        uint256 forkId = vm.createFork("https://eth-mainnet.g.alchemy.com/v2/VZH1EtzO3RVWYSXs523zfhFzlO6KHnr6");
        vm.selectFork(forkId);

        vm.startPrank(deployer);
        lock = new Lock();
        lockList = new LockList(deployer);
        
        // Initialize the Lock contract with necessary configurations
        lock.initialize(address(lockList), 15000, 35000, deployer);
        _stakingToken = new MockToken("stakingToken", "stkToken", 18);
        _rewardToken = _stakingToken;
        rewardTokens.push(address(_rewardToken));

        // Configure reward token and staking token settings
        lock.addReward(address(_rewardToken));
        lock.setStakingToken(address(_stakingToken));
        lockPeriod.push(10);
        lockPeriod.push(20);
        lockPeriod.push(30);
        lockMultiplier.push(1);
        lockMultiplier.push(2);
        lockMultiplier.push(3);
        lock.setLockTypeInfo(lockPeriod, lockMultiplier);

        // Transfer ownership of locker lists to Lock contract
        _stakingToken.mint(user1, 500e18);
        _stakingToken.mint(user2, 500e18);
        _stakingToken.mint(user3, 500e18);
        _rewardToken.mint(deployer, 100000e18);
        lock.setTreasury(address(0x4));
        lockList.transferOwnership(address(lock));
        vm.stopPrank();

        // Approve the Lock to manage staking tokens on behalf of users
        vm.prank(user1);
        _stakingToken.approve(address(lock), 10000e18);
        vm.prank(user2);
        _stakingToken.approve(address(lock), 10000e18);
        vm.prank(user3);
        _stakingToken.approve(address(lock), 10000e18);
        vm.prank(deployer);
        lock.setDefaultRelockTime(10);
    }

    function testFunctionality() public {
        // User 1 stakes 500 gamma with 1 multiplier
        vm.prank(user1);
        lock.stake(500e18, user1, 0);

        // User 2 stakes 500 gamma with 1 multiplier
        vm.prank(user2);
        lock.stake(500e18, user2, 0);

        // User 3 stakes 500 gamma with 1 multiplier
        vm.prank(user3);
        lock.stake(500e18, user3, 0);
        
        // Deployer add rewards and notify
        vm.startPrank(deployer);
        _rewardToken.transfer(address(lock), 10000e18);
        address[] memory rewardTokensForNotify = new address[](1);
        rewardTokensForNotify[0] = address(_rewardToken);
        lock.notifyUnseenReward(rewardTokensForNotify);
        vm.stopPrank();

        // User 1 gets rewards
        vm.prank(user1);
        lock.getAllRewards();
        
        // User 2 gets rewards
        vm.prank(user2);
        lock.getAllRewards();
        
        // User 3 gets rewards
        vm.prank(user3);
        lock.getAllRewards();

        // User 1 trys to early exit (he could try lateExit and withdrawLate too)
        vm.prank(user1);
        vm.expectRevert();
        // Balance of tokens in the contract is not enough since they are distributed as rewards, so this will revert
        lock.earlyExitById(0);
    }
}
```

<details>
<summary> Console output </summary>
As you will see, the balance will be insufficient.
<img width="1144" alt="Screenshot 2024-05-20 at 08 50 45" src="https://github.com/sherlock-audit/2024-05-gamma-staking-zarkk01/assets/77061323/d60ae422-1fa4-41c9-89bf-b59acae28bb9">
</details>

## Impact
Users will be unable to withdraw their staked `GAMMA` amount since it will have be distributed as rewards to every participant. Also, the whole protocol's reward distribution mechanism will be considered broken since the staked amounts are blended with the reward amounts and, in the end, either someone who wish to receive his rewards or someone who wants to exit will not be able to do so.

## Code Snippet
This is the vulnerable code snippet where the balance of `GAMMA` tokens is used for counting rewards and therefore will be distrbuted :

```solidity
    function _notifyUnseenReward(address token) internal {
        if (token == address(0)) revert AddressZero(); // Ensures the token address is not zero.
        Reward storage r = rewardData[token]; // Accesses the reward data for the given token.
        // @audit In the balanceOf(), there is also the staked amounts.
@>        uint256 unseen = IERC20(token).balanceOf(address(this)) - r.balance; // Calculates the amount of new, unseen rewards.

        if (unseen > 0) {
            _notifyReward(token, unseen); // Updates the reward data if there are new rewards.
        }

        emit NotifyUnseenReward(token, unseen); // Emits an event to log the notification of unseen rewards.
    }
```
[Link to code](https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L471)

## Tool used
Manual code inspection, Solodit

## Recommendation
Consider not using `GAMMA` token for both staking and rewards.

**Comment by zarkk01** [comment]
Hey @santipu03 ,

Thanks for your comment on my finding but I believe that it should be valid due to these reasons : 

1. Developer clearly says that he will use GAMMA for staking. He, also, writes code that lets him use GAMMA for staking. Since he says that he WILL do it and he developed the codebase in a way that he CAN do it, I think it is safe to assume that he will indeed use do it (use GAMMA for staking and rewards). 
2. Owner is trusted means that he will not behave MALICIOUSLY, not that he will not do things that he intends to do, have said that he will do and developed the codebase such this to do them.
3. The architecture of the code that the team (which made the statements as shown in the finding) built and developed can use GAMMA for staking and rewards (as they said they will do), so using GAMMA for staking and rewards is not going against the architecture of the code. The architecture is theirs as well as the intentions which are clearly stated when they say that "we can assume GAMMA for staking and rewards".

At the end, I believe that we should assume that they developed the codebase and the architecture of it with their intentions in mind and their intentions are to use GAMMA for staking and rewards. For these reasons, I believe that the finding should be valid (impact : high, likelihood : 100% (they said that it will happen and they developed the code so to happen)).

Again, thank you for your time and giving this issue a second eye regardless of your final decision which will, of course, be respected.

**Comment by IWildSniperI** [comment]
@santipu03 
> All owner functions are fully trusted according to the README:
> 
> > There would mainly be the owner role. Any function that contains the onlyOwner modifier would be a fully trusted function.
> 
> For this reason, any action that the owner may take to bypass a check from the code is considered invalid because the owner is fully trusted and thus it makes no sense for them to try to go against the same architecture of the contract.

problem here is that its not against the owner intent,
he clearly stated that 
> he wants gamma as staking && || as rewards
so the assumption here is not him acting maliciously 

Quoted from judging rules

> Watsons are expected to keep up to date with the contest's Discord channel as important announcements impacting judging may arise. They should keep in mind that any message the Sponsor sends will be considered a source of truth.

code is never a source of truth in judging, if they want to make it but the code doesn't seem to do so then it lies under the following rule too
> Breaks core contract functionality

so the functionality intent of the contract as stated from dev is to set gamma as staking and reward


to wrap up, this is considered to me valid med or border line high as it contradict the intent of the dev and or breaks the contract accounting functionality if it actually set as staking and reward

**Comment by 0xreadyplayer1** [comment]
![image](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/assets/170161435/deeae885-18ad-455e-a12f-dbd51007863a)

while you people continue , the issue seems known from previous audit : )

**Comment by zarkk01** [comment]
Hey @0xreadyplayer1 ,

Thanks for your comment. This issue is not in the known bugs of the contest page : 
<img width="666" alt="Screenshot 2024-05-29 at 16 22 12" src="https://github.com/sherlock-audit/2024-05-gamma-staking-judging/assets/77061323/08929b8c-9c35-495e-9312-82c11fd792db">
That means that a bug is in the codebase which is NOT in the known bugs, so we have to report it and should be considered valid. Also, the sherlock rule says clearly : 
<img width="656" alt="Screenshot 2024-05-29 at 16 40 09" src="https://github.com/sherlock-audit/2024-05-gamma-staking-judging/assets/77061323/d38b0c50-f209-41a5-94ac-35ba03acd961">
But this is not update contest and there is no `won't fix` statement.

Thanks and we will be waiting for @santipu03 opinion on this.

**Comment by santipu03** [comment]
The deciding factor that led me to invalidate this issue is the explicit check in `addReward` function:

https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L175
```solidity
if (_rewardToken == stakingToken || rewardTokenAdded[_rewardToken]) revert InvalidRewardToken();
```

This means that the developers are aware of this issue, even more so considering that this issue was already reported in the last audit. Everything here leads me to think that the discord statement was probably a mistake by that developer.

**Comment by zarkk01** [comment]
I understand what you are saying but I believe that as per Sherlock rules and according to sources of truth this issue should be valid. 

The issue follow the rules of severity since loss of funds will happen and also follow the sources of truth. We, as auditors. can not "arbitrary" assume what dev team is aware of and what is not, that's what "Known Bugs" section is for. This bug was **not** there.

Also, we  can not say that something devs are saying is a mistake **after** the audit. Developers said that "GAMMA will be used as a staking and reward token"  **clearly over and over again**. During the audit, we have to interpret this as the source of truth and we can not judge what they want to do. We are here to find bugs based on what they want and will do & what they code can do. __During the audit, we can not say if something they want to do is mistake__. They are the developers, they wrote the code and they want to do it. If what they want to do is exploitable, that's our job to unhid it and this report is the proof of concept for that. 

Also, saying after the end of the audit that something developers stated  were **"mistake"**,  doesn't seem valid since we, watsons, should assume that what they are saying is the truth from the start and during the audit. We are supposed to rely on their codebase and their stated intentions (during the audit and what is appeared in the contest page) as source of truth.

Once again, I thank you very much for taking time to comment again but I think that if we want to follow the Sherlock rules as they are, this issue should be valid. I will be happy to hear your thoughts on this new perspective.

**Comment by IWildSniperI** [comment]
i will not add more comments not to spam
my comment clearly clarify the problem
thx @santipu03 for your comment any way
