### ISSUE TITLE
samuraii77 - Linear decrease of the penalty is not properly implemented

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-gamma-staking-judging#122]
samuraii77

medium

# Linear decrease of the penalty is not properly implemented

## Summary
Linear decrease of the penalty is not properly implemented
## Vulnerability Detail
Upon exiting out of the staking early, users are obliged to pay a penalty based on how early they have exited. Users can choose their lockup period as well as multiplier, a longer lockup period results in a bigger multiplier that is used to compute their rewards. The way the penalty is calculated however, leaves a possible way for users to game the system.

This is how the penalty gets computed:
```solidity
...
penaltyFactor = (unlockTime - block.timestamp) * timePenaltyFraction / lockPeriod + basePenaltyPercentage;
...
penaltyAmount = userLock.amount * penaltyFactor / WHOLE;
```
`unlockTime - block.timestamp` can be at most equal to `lockPeriod`. Thus, the maximum value for the `penaltyFactor` would be equal to the `timePenaltyFraction` which is 35% according to the inline docs. That means that if there was an option for a user to stake for let's say, a 100 years and thus, get a very large multiplier, he would still receive at most `35% + basePenaltyPercentage` as a fee even if he exited the protocol immediately. This allows users to use large lockup periods and multipliers to their advantage by exiting the system immediately after for example, staking before adding of rewards, claiming the rewards and withdrawing right after while still being in profit thanks to the large multiplier and still paying the same fee as someone who decided to lockup his funds for let's say, just 5 minutes with a small multiplier.
## Impact
Linear decrease of the penalty is not properly implemented
## Code Snippet
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/703fd3604069489937037f20490ec8c492c0508e/StakingV2/src/Lock.sol#L569-L586
## Tool used

Manual Review

## Recommendation
Do not calculate the penalty as a ratio of the lockup period but based on the amount of time they are early by when exiting.

**Comment by samuraii77** [comment]
Escalate

I believe the issue should be valid.
Let's imagine 2 possible lock-up options:
 - 1 month, 1x multiplier
 - 10 years, 10x multiplier
 
With the vector submitted in the issue, any user has a lever that he can use in order to potentially game the system. If 2 users stake tokens, one of them using the first lock-up option and the other one with the second lock-up option and both exit in the first second, both will owe the same amount of fees (if they staked the same amount of money). This clearly allows malicious users to use large multipliers and large lock-up periods in order to game the system and still profit even after the fees for early exits. Over a long enough timeframe, it is guaranteed for there to be situations where a malicious user can successfully utilize the bigger multiplier and game the system.

Also, a trusted admin is supposed to not do things that harm the protocol. Depositing rewards is in no way, shape or form, a way in which he can harm the protocol, it is a normal admin behavior. According to the contest page, rewards will be sent periodically, there will not be any special checks to determine whether a malicious user could arbitrage the rewards. Rewards can also be deposited by any party including external integrations at any time.

The issue reported clearly gives malicious users a very high chance to game the system, thus the issue should be a valid medium.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> I believe the issue should be valid.
> Let's imagine 2 possible lock-up options:
>  - 1 month, 1x multiplier
>  - 10 years, 10x multiplier
>  
> With the vector submitted in the issue, any user has a lever that he can use in order to potentially game the system. If 2 users stake tokens, one of them using the first lock-up option and the other one with the second lock-up option and both exit in the first second, both will owe the same amount of fees (if they staked the same amount of money). This clearly allows malicious users to use large multipliers and large lock-up periods in order to game the system and still profit even after the fees for early exits. Over a long enough timeframe, it is guaranteed for there to be situations where a malicious user can successfully utilize the bigger multiplier and game the system.
> 
> Also, a trusted admin is supposed to not do things that harm the protocol. Depositing rewards is in no way, shape or form, a way in which he can harm the protocol, it is a normal admin behavior. According to the contest page, rewards will be sent periodically, there will not be any special checks to determine whether a malicious user could arbitrage the rewards. Rewards can also be deposited by any party including external integrations at any time.
> 
> The issue reported clearly gives malicious users a very high chance to game the system, thus the issue should be a valid medium.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by santipu03** [comment]
I still believe this issue should be invalid according to my [first comment](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/122#issuecomment-2132304041). 

If admins decide to start sending huge rewards in comparison to the total staked value, they're making the penalty system useless because stakers will have enough funds to exit early with profits, that's why it makes no sense to do that being TRUSTED admins. And in case they have tons of rewards to distribute and so little staked value, they would increase the penalties to prevent this kind of arbitrage. 

Lastly, remark that the scenarios described are unrealistic because the sponsor already specified that the multipliers will be `1x` and `2x`, not `10x`.

**Comment by samuraii77** [comment]
I agree that sending huge rewards would make the penalty system less useful. That is exactly why users having access to large multipliers for virtually no extra cost makes a non-profitable attack much more likely and possibly profitable.

**Comment by santipu03** [comment]
For the exact reason that sending huge rewards in a short amount of time will make the penalty system useless, then I assume that the admins won't do that given that they're TRUSTED. In that scenario where the admins have tons of rewards to distribute and a small amount of stakers, it only makes sense to distribute those rewards slowly to attract more stakers, not to distribute them all at once.

**Comment by nevillehuang** [comment]
If larger multipliers are introduced, the penalties are presumed to be upgraded accordingly as mentioned in the contest details [here](https://github.com/sherlock-audit/2024-05-gamma-staking?tab=readme-ov-file#q-are-there-any-hardcoded-values-that-you-intend-to-change-before-some-deployments). Since this are admin controlled variables, I believe this issue to be invalid. 

Planning to reject escalation and leave issue as it is.

**Comment by samuraii77** [comment]
This is the title of the section:
>Are there any hardcoded values that you intend to change before (some) deployments?

These are values that could be changed __before__ the deployment. It is not stated anywhere that they would change afterwards.

**Comment by nevillehuang** [comment]
Still planning to reject escalation and leave issue as it is based on comments [here](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/122#issuecomment-2143111190).

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [samuraii77](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/122/#issuecomment-2137963179): rejected
