### ISSUE TITLE
Honour - Unable to recover inactive reward tokens

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-gamma-staking-judging#226]
Honour

medium

# Unable to recover inactive reward tokens

## Summary

`Lock::recoverERC20` is unable to recover inactive reward tokens

## Vulnerability Detail

From the description of `Lock::recoverERC20()`, [here](https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L651-L652) we can clearify that the admin should be able to recover reward tokens aswell as long as said tokens are inactive(are not actively used for rewards/ have not acumulated rewards), this is further backed by the fact that `Lock::recoverERC20()` only checks the `lastUpdateTimestamp` instead of the `rewardTokenAdded` mapping. However Because the `Lock::addReward()` function updates the `lastUpdateTimestamp` immediately a reward token is added ,this functionality is broken as `Lock::recoverERC20()` assumes the token is active even though it hasn't accumulated any rewards.

## Impact

Medium, possible functionality break

## Code Snippet

https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L180

https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L650-L655

## Tool used

Manual Review

## Recommendation

https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L180

```diff
function addReward(address _rewardToken) external override onlyOwner {
        if (_rewardToken == address(0)) revert InvalidBurn();
        if (rewardData[_rewardToken].lastUpdateTime != 0) revert AlreadyAdded();
        if (_rewardToken == stakingToken || rewardTokenAdded[_rewardToken]) revert InvalidRewardToken();
        rewardTokens.push(_rewardToken);
        rewardTokenAdded[_rewardToken] = true;

        Reward storage reward = rewardData[_rewardToken];
-       reward.lastUpdateTime = block.timestamp;
        emit AddReward(_rewardToken);
    }
```

**Comment by Honour-d-dev** [comment]
@santipu03 i understand your reasoning however i believe you must have misunderstood mine.
My point is that it should still be possible to recover a reward token token sent to the contract provided that reward token hasn't yet been used to accumulate rewards for users.

For example say usdt was added as a reward token but hasn't accumulated any rewards yet or say the token was added but the dao decided not to use it as a reward token for **whatever reason**, however, since there's no way to remove reward tokens in such a case usdt accidentally sent to the contract would be locked even though it hasn't accumulated rewards yet and/or is probably not going to be used to.
And that's because `lastUpdateTime` is updated on `add()` rather than on `notifyReward()`

**Comment by santipu03** [comment]
> My point is that it should still be possible to recover a reward token token sent to the contract provided that reward token hasn't yet been used to accumulate rewards for users.

When a token is added as a reward and some tokens are sent to the contract, anyone can call `notifyUnseenReward` and those tokens will be distributed between all stakers, so there's no need to recover them.
