### ISSUE TITLE
smbv-1923 - Penalty amount would be higher for a staker who stakes for a longer duration compared to a staker who stakes for a shorter period

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-gamma-staking-judging#236]
smbv-1923

high

# Penalty amount would be higher for a staker who stakes for a longer duration compared to a staker who stakes for a shorter period

## Summary
- Penalty amount would be higher for a staker who stakes for a longer duration compared to a staker who stakes for a shorter period
## Vulnerability Detail
- Penalty amount would be higher for a staker who stakes for a longer duration compared to a staker who stakes for a shorter period.
- Let's understand through an example.
- Alice stakes his1e18 assets for 30 days and Bob also stakes his 1e18 for 30 days and they both have same multiplier.
- Here defaultRelockTime = 30 days
- After 20 days Alice  withdraw his stake assests through `earlyExitById()` , she would be imposed 10days * 35% / 30 days + 15% = 11.6 + 15% = 26.6 % on his staked amount.
- Now Bob withdraws his stake after 31 days of staking through `earlyExitById()` , he would be imposed 29 days * 35% / 30 days + 15% = 33.8% on his staked amount.
- Even after staking for more days he has to pay more penalty.

## Impact
- Bob has to pay more penalty amount even though he had staked his amount for longer duration than Alice.
- Even though Bob had completed his LockDuration he would pay more penalty than Alice who didn't even complete his LockDuration. 

## Code Snippet
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L569
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L581
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L578
## Tool used

Manual Review

## Recommendation
- Change the logic of penalty amount  when staked duration has been completed .

**Comment by MD-YashShah1923** [comment]
Escalate
This issue is duplicate of #65 
- My report clearly states with an example where user's who's position is withdrawn through `earlyExitById()`  just after the lockPeriod is ended would suffer losses and have to pay more penalty amount.
- Impacts in both the report is same i.e "Penalty may be greater than expected in earlyExitById()" which i also stated it.
- You can see my example stated above in the report where i mentioned when Bob's position is exited after lockPeriod (31 days ) he would suffer more penalty charges.
- This should be considered as duplicate.

**Comment by sherlock-admin3** [comment]
> Escalate
> This issue is duplicate of #65 
> - My report clearly states with an example where user's who's position is withdrawn through `earlyExitById()`  just after the lockPeriod is ended would suffer losses and have to pay more penalty amount.
> - Impacts in both the report is same i.e "Penalty may be greater than expected in earlyExitById()" which i also stated it.
> - You can see my example stated above in the report where i mentioned when Bob's position is exited after lockPeriod (31 days ) he would suffer more penalty charges.
> - This should be considered as duplicate.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by santipu03** [comment]
This report has nothing to do with #65. 

The root cause of #65 is that calling an exit function near the end of the period can cause extra locking time or extra penalties for the user because the transaction got delayed. 

On the other hand, this report argues that the penalties for re-locked positions might seem unfair because a user who has staked for more time might get more penalized due to re-locking, which is the intended design.

**Comment by MD-YashShah1923** [comment]
In my report i have clearly mentioned what will be the consequences when the earlyExit() is called after the end of period .
For simplicity i rounded up calculation in days rather than seconds or hours and made the calculation according to it.
And i have identified the main issue which #65 signifies and in both the cases the impacts are same as well..

**Comment by nevillehuang** [comment]
Agree with lead judge judgement. For exits of expired locks, the penalty applied should be considered based on the relocked duration. This issue fails to identify the correct root cause of exiting near the end of the period before expiration (it uses an example of a 30 day lock-up and exiting at the 31st day, where in the position has expired).

Planning to reject escalation and leave issue as it is.

**Comment by MD-YashShah1923** [comment]
> Agree with lead judge judgement. For exits of expired locks, the penalty applied should be considered based on the relocked duration. This issue fails to identify the correct root cause of exiting near the end of the period before expiration (it uses an example of a 30 day lock-up and exiting at the 31st day, where in the position has expired).
> 
> Planning to reject escalation and leave issue as it is.

I identified the root cause and i gave the example of 31 days for betterment of my calculation so i rounded up in days rather than seconds or minutes. The main root cause of the issue is exiting when lock period ends would create more penalty calculations and the user would have to wait more which i have clearly stated in my report.
This should be considered as a duplicate.

**Comment by nevillehuang** [comment]
Still planning to reject escalation based on comments [here](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/236#issuecomment-2143124112). Exiting when lock period ends (expired) is completely different from exiting before expiration.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [MD-YashShah1923](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/236/#issuecomment-2139261898): rejected
