### ISSUE TITLE
ydlee - The calculation of the remaining unlock period is incorrect.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-gamma-staking-judging#256]
ydlee

high

# The calculation of the remaining unlock period is incorrect.

## Summary
In `calcRemainUnlockPeriod`, the calculation of the remaining unlock period is incorrect when current timestamp is larger than the lock time. The impacts are:
1. The penalty amount of early exit is wrong, more or less than expected.
2. The resulting unlock time is wrong, meaning that users are unable to unlock their tokens at the expected time.

## Vulnerability Detail
In L605, when `block.time > lockTime`, the first `lockPeriod` should be subtracted before modulo `lockPeriod` or `defaultRelockTime`. For example
```solidity
lockPeriod = 10 Days
defaultRelockTime = 7 Days
block.timestamp - lockTime = 12 Days
reaminUnlockPeriod = 7 - 12 % 7 = 2 Days  (L605)
```
However, the user's tokens are first locked for `10 Days` during the first period (i.e. `lockPeriod`), and then the tokens are then re-locked for `7 Days` during the second period (i.e. `defaultRelockTime`). After `12 Days`, only `2 Days` have passed in the second locking period, so the remaining unlocking period should be `5 Days`, not the `2 Days` calculated above.

```solidity
596:    function calcRemainUnlockPeriod(LockedBalance memory userLock) public view returns (uint256) {
597:        uint256 lockTime = userLock.lockTime;
598:        uint256 lockPeriod = userLock.lockPeriod;
599:        
600:        if (lockPeriod <= defaultRelockTime || (block.timestamp - lockTime) < lockPeriod) {
601:            // If the adjusted lock period is less than or equal to the default relock time, or if the current time is still within the adjusted lock period, return the remaining time based on the adjusted lock period.
602:            return lockPeriod - (block.timestamp - lockTime) % lockPeriod;
603:        } else {
604:            // If the current time exceeds the adjusted lock period, return the remaining time based on the default relock time.
605:@>          return defaultRelockTime - (block.timestamp - lockTime) % defaultRelockTime;
606:        }
607:    }
```
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L596-L607

## Impact
The calculation of the remaining unlock period is incorrect, as the unlock time is used when calculating the penalty amount for early exits and withdrawing unlocked token, so the impacts can be:
1. The penalty amount of early exit is wrong, more or less than expected.
2. The resulting unlock time is wrong, meaning that users are unable to unlock their tokens at the expected time.

## Code Snippet
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L596-L607

## Tool used

Manual Review

## Recommendation
```solidity
    function calcRemainUnlockPeriod(LockedBalance memory userLock) public view returns (uint256) {
        uint256 lockTime = userLock.lockTime;
        uint256 lockPeriod = userLock.lockPeriod;
        
        if (lockPeriod <= defaultRelockTime || (block.timestamp - lockTime) < lockPeriod) {
            // If the adjusted lock period is less than or equal to the default relock time, or if the current time is still within the adjusted lock period, return the remaining time based on the adjusted lock period.
            return lockPeriod - (block.timestamp - lockTime) % lockPeriod;
        } else {
            // If the current time exceeds the adjusted lock period, return the remaining time based on the default relock time.
-            return defaultRelockTime - (block.timestamp - lockTime) % defaultRelockTime;
+            return defaultRelockTime - (block.timestamp - lockTime - lockPeriod) % defaultRelockTime;
        }
    }
```

**Comment by Tri-pathi** [comment]
@santipu03  Thanks for judging

Due to this issue, the penalty amount calculation is flawed impacting

1. User's loss if the penalty amount exceeds the original amount.
2. Protocol loss if the penalty amount is less than expected.

Given this high impact and likelihood of both scenarios, the severity of this issue should be classified as high 
SOURCE - https://docs.sherlock.xyz/audits/judging/judging#iv.-how-to-identify-a-high-issue

**Comment by Dliteofficial** [comment]
escalate

**I don't think this finding is correct because the remaining unlock period is calculated as per the expected design: if the lock period is more than the default lock period, the default lock period is the basis**

Using the POC in the report where the lock period is 10 days, the timestamp - lock period is 12 days, although only 2 days have passed since the lock period has passed and the remaining time should be 8 days, but because of the if-else statement that uses default lock time (7 days) instead of 10 days when lock period is higher, the true time passed is 5 days and the remaining time should be 2 days.

**Comment by sherlock-admin3** [comment]
> escalate
> 
> **I don't think this finding is correct because the remaining unlock period is calculated as per the expected design: if the lock period is more than the default lock period, the default lock period is the basis**
> 
> Using the POC in the report where the lock period is 10 days, the timestamp - lock period is 12 days, although only 2 days have passed since the lock period has passed and the remaining time should be 8 days, but because of the if-else statement that uses default lock time (7 days) instead of 10 days when lock period is higher, the true time passed is 5 days and the remaining time should be 2 days.

You've deleted an escalation for this issue.

**Comment by ZdravkoHr** [comment]
@Dliteofficial, you swapped the places of time passed and time remaining. Read your exaple again, if the stakes are relocked for 7 days and 2 have passed, there are 5 days more until the end

**Comment by Dliteofficial** [comment]
Block.timestamp - lockTime is 12 days right. That's what it says in the POC. Our default time is 7 days. That means 5 more days has passed and there are 2 more days to complete the cycle. Time remaining is 2 more days

**Comment by Dliteofficial** [comment]
My example is comparing what is in the report and what it should based on what the codebase says. 

Given that the default is now the base, if 12 days has pass, the modulus operation is going to equate to 5 days more has passed + the default 7 days since default < lockPeriod. 

7 - 5 = 2

**Comment by Dliteofficial** [comment]
Is there something I am missing

**Comment by ZdravkoHr** [comment]
@Dliteofficial, oh, now I see where your logic comes from. You are assuming that the stakes will be locked n times for 7 days. 

In reality, the first lock will take 10 days and only after that will they be relocked for 7 days. So when 12 days pass, the first lock period has finished and we are 2 days in the new 7-days long period, which means there are 5 more days until the period is over.

**Comment by Dliteofficial** [comment]
Well then, I don't think this issue should be the flagship for this finding. Thanks for explaining @ZdravkoHr

**Comment by SUPERMAN-I4G** [comment]
Escalate

[@santipu03] I believe this is issue is infact not valid.

1. The values used by the ```Watson``` to prove this is an issue is an illusion.
2. There’s no difference between the initial calculation and the fix. It does the same thing and gives the same result.

Reason: 
According to the protocol:
> …in reality, the minimum lock time will be ```30 days``` and the ```defaultRelockTime``` should be equal to minimum lock time…

If we use realistic values we will in fact see that this issue is invalid. Now:

```lockPeriod = 180 Days```
```defaultRelockTime = 30 days```
```block.timestamp - lockTime = 181 Days```
Using protocol’s initial calculation:
```reaminUnlockPeriod = 30 - (181) % 30 = 29 Days```
Using Watson’s recommended fix:
```reaminUnlockPeriod = 30 - (181 - 180) % 30 = 29 Days```

The small unrealistic values used by the ```Watson``` is what alludes the validity of this issue but in fact it’s a false assumption. Because the minimum lock time will be 30 days and the ```defaultRelockTime``` should be equal to minimum lock time therefore for users to use this calculation;
```defaultRelockTime - (block.timestamp - lockTime) % defaultRelockTime;```
They will have to always pass their lock period which is never less than 30 days. 

The sponsors can confirm this. You can also carefully look at the test file (```UnlockCalculation.t.sol```) provided by the protocol. 

Cheers.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> [@santipu03] I believe this is issue is infact not valid.
> 
> 1. The values used by the ```Watson``` to prove this is an issue is an illusion.
> 2. There’s no difference between the initial calculation and the fix. It does the same thing and gives the same result.
> 
> Reason: 
> According to the protocol:
> > …in reality, the minimum lock time will be ```30 days``` and the ```defaultRelockTime``` should be equal to minimum lock time…
> 
> If we use realistic values we will in fact see that this issue is invalid. Now:
> 
> ```lockPeriod = 180 Days```
> ```defaultRelockTime = 30 days```
> ```block.timestamp - lockTime = 181 Days```
> Using protocol’s initial calculation:
> ```reaminUnlockPeriod = 30 - (181) % 30 = 29 Days```
> Using Watson’s recommended fix:
> ```reaminUnlockPeriod = 30 - (181 - 180) % 30 = 29 Days```
> 
> The small unrealistic values used by the ```Watson``` is what alludes the validity of this issue but in fact it’s a false assumption. Because the minimum lock time will be 30 days and the ```defaultRelockTime``` should be equal to minimum lock time therefore for users to use this calculation;
> ```defaultRelockTime - (block.timestamp - lockTime) % defaultRelockTime;```
> They will have to always pass their lock period which is never less than 30 days. 
> 
> The sponsors can confirm this. You can also carefully look at the test file (```UnlockCalculation.t.sol```) provided by the protocol. 
> 
> Cheers.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ZdravkoHr** [comment]
@SUPERMAN-I4G, this is because the issue wrongly says the problem occurs when the lock period is greater than the defaultRelockTime, which is not true.

The problem actually occurs when the lockPeriod can't be divided by defaultRelockTime.

@santipu03, maybe this issue really doesn't show the real problem compared to its duplicates?

**Comment by Dliteofficial** [comment]
See what I mean @ZdravkoHr and honestly, it is best to use 30 days. There won't be a lock with 7 or 10 days and frankly I am still inclined to side with @SUPERMAN-I4G until a duplicate finding or some other POC can demonstrate this well

**Comment by ZdravkoHr** [comment]
@Dliteofficial, you can read #48 or #206

**Comment by Dliteofficial** [comment]
@santipu03 this report doesn't define this vulnerability. As a suggestion, frankly it should be removed. #48 or #206 did the job

**Comment by 0xh2134** [comment]
The issue is valid only if the `lockPeriod` cannot be evenly divided by the `defaultRelockTime`.

**For example:**
> lockPeriod = 181 Days
defaultRelockTime = 30 days
block.timestamp - lockTime = 182 Days
Using protocol’s initial calculation:
reaminUnlockPeriod = 30 - (182) % 30 = 28 Days (should be 29 since only 1 day passed)

However based on sponsor's comments in #69, the `lockPeriod` can always be evenly divided by `defaultRelockTime`, so this issue should be invalid, or #69 should be also valid.

**Comment by SUPERMAN-I4G** [comment]
@ZdravkoHr, @Dliteofficial & @0xh2134 

Realistically; ```lockPeriod``` will be set as:
```30 days, 60 days, 90 days, 180 days & 360 days```.

```lockPeriod``` will never be 31 days, 61 days, 181 days or even 361 days. Therefore there’s no possibility of the ```lockPeriod``` not being evenly divided by the ```defaultRelockTime```. Because if that happens the module logic will always return with wrong values. It’s a general principle which I am sure the protocol is aware. 

Because when you carefully look at the test file (```UnlockCalculation.t.sol```), the protocol showed instances of ```lockPeriod = 30, 60, and 360 days```. So it doesn’t make sense why the protocol will set ```lockPeriod``` that won’t evenly divided by ```defaultRelockTime```. The sponsors even confirmed that. 

Therefore @santipu03 this set of issue should be invalid.

**Comment by ZdravkoHr** [comment]
The values in the test, as well as in the screenshot are example values. Nowhere it was documented the lockPeriod will be divisable by the relockPeriod. The code allows settin such values.

In addition, the protocol team did fix this issue, so I disagree this was intended

**Comment by SUPERMAN-I4G** [comment]
@ZdravkoHr test files are realistic assumptions made by the protocol and serve as a guideline.
 
As per the protocol:
> See the test for UnlockCalculation.t.sol to understand the behavior of this function.

Like I have said already, it’s a general principle when using the module logic. Nothing new. 

Finally the protocol fixing this issue doesn’t guarantee the validity of an issue as the Lead Judge has the final decision to validate & invalidate an issue. And in this case there’s no difference between the initial code and fix because they will give the same result in context to the protocol’s realistic application (i.e ```lockPeriod``` will always be evenly divisible by ```defaultRelockTime```)

**Comment by Dliteofficial** [comment]
That seems to be happening lately. They just may have introduced a new bug if discussions such as these haven't been finalised. I believe the lead judge or lead Watson should have cautioned against that.

**Comment by santipu03** [comment]
I agree that this issue will only have some impact when `lockPeriod` is not a multiple of `defaultRelockTime`, as reports #69 and #48 correctly demonstrate. 

However, if consider [this comment](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/69#issuecomment-2134114780) from the sponsor as a source of truth, then this issue will never be triggered because all the lock periods planned by the sponsor are multiple of `defaultRelockTime`, making this issue invalid. On the other hand, if we consider that the plans by the sponsor are just _possibilities_ and are not certain, this issue would be valid.

**Comment by samuraii77** [comment]
In that case, if this issue remains valid, I believe it is fair to validate #69 as well because if we deem the words of the sponsors about the lock periods and multipliers as source of truth, both issues should be invalid but if we deem them as just an example (which I believe they are judging by the language they are using as explained in my escalation on issue 69), then both issues should be valid.

**Comment by Tri-pathi** [comment]
@santipu03 

Nowhere on the contest page, in the documentation, or in the comments has it been mentioned that the lock period will be an integral multiple of defaultRelockTime. So, how and from where are these assumptions being made?

>> I agree that this issue will only have some impact when lockPeriod is not a multiple of defaultRelockTime

Only some impact?  Penalty amount calculation is incorrect  which clearly affect the both protocol and users

**Comment by SUPERMAN-I4G** [comment]
@samuraii77 is absolutely correct. If this issue is valid not only #69 should be valid but a lot more issues like #151 will be deemed valid. Why because if we’re validating issues based on examples (which could be false) then a lot of issues will be valid. So for me it’s either we choose the words of the sponsors as source of truth and invalidate the issues else a lot of issues will be valid based on watson’s examples. It’s your call @santipu03. As the lead judge any final assessment you make will be respected.

@Tri-pathi  I would suggest you take a quick research on module arithmetic logic in Defi. Look at some of other popular protocol’s similar implementation and you will understand better or better off look into the test file (```UnlockCalculation.t.sol```) as the protocol clearly said:

> See the test for ```UnlockCalculation.t.sol``` to understand the behavior of this function.

Cheers.

**Comment by Tri-pathi** [comment]
In #69  `setLockTypeInfo()` is controlled by admin and he is trusted and this is how every admin function works whether it is changing fee prams, updating old price Feed , changing treasury, blacklisting  etc etc 

For #151 Lead judge already clarified the reasons as this is tradeoff between design and trusted admin responsibility which is not an issue.

>> See the test for UnlockCalculation.t.sol to understand the behavior of this function.

These are the unit test which just make sure that codes give expected output for some inputs. Next thing I'm gonna hear that you can only stale the amount which is used in unit test .


> Hierarchy of truth: If the protocol team provides no specific information, the default rules apply (judging guidelines).
>If the protocol team provides specific information in the README or CODE COMMENTS, that information stands above all judging rules. In case of contradictions between the README and CODE COMMENTS, the README is the chosen source of truth

Again quoting `Nowhere on the contest page, in the documentation, or in the comments has it been mentioned that the lock period will be an integral multiple of defaultRelockTime so you can't assume anything. ` .  



Anyone who is commenting in this issue please reply to the point, Just add why this is invalid/valid wrt Sherlock judging rules. We aren't here for stories

**Comment by SUPERMAN-I4G** [comment]
@Tri-pathi you just added more context to why this issue should be invalid, lol.
 
> In #69 setLockTypeInfo() is controlled by admin and he is trusted and this is how every admin function works whether it is changing fee prams, updating old price Feed , changing treasury, blacklisting etc.

So why do you believe that the admin will set ```lockPeriod``` that won’t evenly divided by ```defaultRelockTime``` since the admin is TRUSTED (i.e won’t take any decision that will cause issues for the protocol) since admin is aware of such modulo implications.
And saying protocol didn’t provide context to this issue is absurd. If these context aren’t enough then I don’t know how much more information you need:
> we use seconds for simplicity, but in reality, the minimum lock time will be 30 days and the ```defaultRelockTime``` should be equal to minimum lock time…

> The unlock time is dictated by modulo logic in function ```calcRemainUnlockPeriod```. So if the lock time were 30 days, and the user staked for 50 days, he would have been deemed to lock for a full cycle of 30 days, followed by 20 days into the second cycle of 30 days, and thus will have 10 days left before he can withdraw his funds.

> See the test for ```UnlockCalculation.t.sol``` to understand the behavior of this function.

And that doesn’t mean any assumption made should be accepted because you deemed protocol didn’t provide enough context. 

Seriously this issue doesn’t need more discussion. The earlier discussions are sufficient enough for anyone to understand and see why it should be invalid therefore I won’t be commenting on this issue again. The lead judge has the final say.

cheers.

**Comment by nevillehuang** [comment]
I am inclined to believe this issue is invalid, since ultimately, the issue is triggered by what is considered a wrong admin input  when setting up lock durations. It is also highlighted as follows:

> In the PenaltyCalculations, we use seconds for simplicity, but in reality, the minimum lock time will be 30 days and the defaultRelockTime should be equal to minimum lock time, but in case its not, the penalty should be based on the original lockPeriod.

And based on discussions by admins on how it will be setup within discord, their configuration is correct (all multiples of 30) so this issue will never be triggered. Planning to accept escalation and invalidate issue.

**Comment by pkqs90** [comment]
Just joining this chat @nevillehuang @santipu03.

I think this issue is obviously valid, and have confirmed with the sponsor @bjp333 during the contest, to which we have also arrived at the mitigation method which is the same as what this issue states.

The sponsor's comment is only a case "in practice", but they never said this couldn't be changed. I think it is very unfair to say that admins will only use the configuration as their discord comment.

Actually, before this issue was brought up, the sponsors did not realize that unlock period didn't work as expected if `lockPeriod` is not a multiple of `defaultRelockTime` (@bjp333 can help confirm this). Which means if this issue was not brought up, they may change it to values that doesn't work expectedly.

At last, this issue has 1) brought value to the sponsors, 2) sponsors confirmed and provided a fix. But yet if this is still considered *invalid*, I'm just not sure of what the criteria here is ...

**Comment by nevillehuang** [comment]
@pkqs90 As far as I know, it is always assumed that if admins are trusted they will have the correct configurations in place. Since both lock durations and default lock durations can be changed, I believe this issue should remain invalid (This is highlighted in [point 5](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid))

**Comment by pkqs90** [comment]
@nevillehuang I understand what you are saying, according to Sherlock rules, the trusted admins are to blame instead of the incorrect code-implementation for this issue.

Jumping out of the rules of Sherlock, I'd like to point out that code-implementation wise, this is an obvious bug (not going to use the word issue here) because the formula used in the code contradicts to the original design of the protocol. The formula is only correct under a strict constraint `lockPeriod % defaultRelockTime == 0`.

Now coming back to the rules of Sherlock, it seems that even though this code-implementation bug exists, since the admins are trusted, they are always expected to correctly set `lockPeriod` and `defaultRelockTime` for this constraint.

If this kind of issue is invalidated, I think it simply discourages future watsons to discover such formula related issues, and would just assume admin always know what they are doing and what to expect (which in this specific case, the protocol team does not).

**Comment by Tri-pathi** [comment]
@nevillehuang 
>  if admins are trusted they will have the correct configurations in place

The Protocol team never said that they want to work with just some fixed lock periods, and I don't understand why people keep saying that the protocol will use only fixed lock periods. They have always intended to work with every lock period greater than the minimum lock period, both before and after the contest. This is why they worked on the fixes mentioned by @pkqs90.

**Comment by nevillehuang** [comment]
I agree, this does limit the lock durations to only multiples of defaultlockperiod. But as far as I know there are no evidence (documentation/code comment) that lock durations will never be a multiple of default lock time? Let me know if there is, because if so it can be medium severity.

If there is no concrete evidence, we go back to sherlock rules that it is still invalid since the whole issue is dependent on variables configured by admin.

**Comment by 0xRajkumar** [comment]
I believe it's valid because the specification doesn't mention whether lock durations must be multiples of the default lock time. Therefore, we should consider both possibilities: when the lock duration is a multiple and when it's not. This means admins should be able to set lock durations even if they're not multiples of the default time.

**Comment by 0xRajkumar** [comment]
Both possibilities — when the lock duration is a multiple and when it's not — should be considered as correct configurations.

**Comment by SUPERMAN-I4G** [comment]
@0xRajkumar & @Tri-pathi 
With all indications, this is probably the first time you both are coming across a protocol using the modulo logic to calculate remaining time. 

You need to understand that it’s the protocol’s intended design of setting minimum ```lock time``` and  ```defaultRelockTime``` to ```30 days``` is what makes this issue invalid. In both ```if & else``` formulas, ```30 days``` is always going to be used (either as ```LockPeriod``` or as ```defaultRelockTime```) therefore the ```lockPeriod``` will always have to be an integral multiple of the set ```defaultRelockTime (i.e 30 days)```. It definitely doesn’t make sense why admin will set ```lockPeriod``` as ```35 days``` for example. The protocol confirmed that’s never going to happen because in fact the modulo logic will always return wrong values.

If the protocol had set ```defaultRelockTime = 5 days``` then the ```lockPeriod``` can be ```35 days``` (or any multiple of 5). Or If the protocol had set ```defaultRelockTime = 10 days``` then the ```lockPeriod``` can be ```50 days``` or at best if the protocol had set ```defaultRelockTime = 1 days``` then the ```lockPeriod``` can be any value else you cannot set ```defaultRelockTime``` as ```30 days``` and use ```35 days``` or similar as ```lockPeriod```. I repeat that’s the general principle of modulo logic. Please kindly do a small research and check popular protocols that implement similar logic or best look at the test file provided. 

This issue doesn’t need to be stretched this long. It’s very simple to understand why it should be invalid by anyone. Just leave the shoes of the Watson who reported this issue and try seeing from others perspective. 

Cheers.

**Comment by 0xRajkumar** [comment]
My points: 
1. The documentation does not specify that the lock duration must be a multiple of the default lock time.
2. They are saying that 'the minimum lock time will be 30 days, and the default relock time should be equal to the minimum lock time' but they are also indicating that 'in case it's not' meaning the default relock time can be different from the default lock time.
3. Based on these points, it's clear that both scenarios (when the lock duration is a multiple and when it's not) are valid configurations. Admin should have the ability to set them accordingly, and it wouldn't be considered an error on their part.

@SUPERMAN-I4G Share with me when they mentioned their intended design of setting the minimum lock time and defaultRelockTime to 30 days?

**Comment by SUPERMAN-I4G** [comment]
@0xRajkumar please read earlier discussion. Refrain from adding comments that doesn't add any new point to the argument. And respectfully I think we have all said enough. The lead judge will have and has the final say so let’s respect that. No more comments will be coming from me so thank you for your time.

Cheers.

**Comment by nevillehuang** [comment]
@0xRajkumar @pkqs90 I still don't see concrete evidence that lock durations should not be a multiple of defaultLockPeriod. The sponsor fixing and gaining value is never used as a reason to validate issues in sherlock. You could try taking a look at the docs/tests/code comments and see if there is. The contest details on "in case it's not" is mentioning about specific lock periods regarding penalties computed in the `if` block not the `else` block, and has no indication that lock periods will not be a multiple of default lock period.

Using the argument of "it was not mentioned anywhere" is not valid because sherlock rules assumes trusted admin will never make mistakes when configuring variables for the contract. If no concrete evidence is discovered, I will go by the configurations mentioned publicly on discord channels as a source of information, and plan to accept escalation and invalidate the issue.

**Comment by Tri-pathi** [comment]
@nevillehuang 

https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L593
>  The lock period should always be the lesser of the user's own lock period or the default lock period. 

https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L601

>If the adjusted lock period is less than or equal to the default relock time

These are the comments in codebase. which check for `lock period is less than or equal to the default relock time` i guess if lockPeriod is only multiple of default relock time there shouldn't be check for `lockperiod < default relock time`


PS:  I'm not sure how to provide concrete evidence. I thought a POC was necessary for valid issues. Some SR might say that these code/comments are wrong/meaningless. So From the next contest I will try to manage a lawyer for proofs. Thankyou

**Comment by nevillehuang** [comment]
After discussions with internal sherlock judges, the final decision is to accept escalation [here](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/256#issuecomment-2141758559) and make this issue invalid.  Based on the intended configuration mentioned in public discord channel [here](https://discord.com/channels/812037309376495636/1241042575381762168/1241414075863273604), this issue will never occur, so based on the following guideline for [hierarchy of truth](https://docs.sherlock.xyz/audits/judging/judging#iii.-sherlocks-standards), I believe this issue is invalid.

> The Sherlock Judge can use public statements up until 24h before the contest ends to override the language in the chosen source of truth

**Comment by bjp333** [comment]
Just looking thru this chat here.  Yeah that was definitely a mathematical mistake on our part to not account for the fact that the lockTimes need to be an exact multiple of defaultRelockTime in order to avoid this mistake, and honestly we were very grateful that @pkqs90 brought up this point.  I agree that this would not have happened in practice due to the configurations we chose, but it's honestly because we got a bit "lucky" in that the lockTimes we chose just so happened to be a multiple of defaultRelockTime.  We changed the formula because it was a pretty egregious mathematical mistake on our part.  

I would differentiate between this case and another case where the users were able to keep their multipliers after their initial lock periods were over because in the latter case, that actually was the intention.  However, in this case, it wasn't the intention for that equation to behave as it did.  I agree that it wouldn't have caused an issue with the configurations that we chose because we got lucky, but it wasn't our intention for the mathematical equation to work like that.

**Comment by WangSecurity** [comment]
> In practice, the staking token will be our governance token that will only have one visible option on frontend for a 30-day lock with defaultLockPeriod also equal to 30 days. The ability to earlyExit will be toggled off by default. On the backend, longer lock periods will be reserved for team and investors who will be staked at the same multiplier as the public. This allows team and investors to lock their tokens and earn revenues from locking without the ability to unstake tokens until they reach the end of their lockPeriods or defaultLock periods.

Still, this information above was available and was in the README file of the repository, hence, it was known information that the only lock period would be 30 days. With that, I believe it would be fair to invalidate this report because this issue wouldn't cause any problems. I don't say the report is invalid, but rather low/info. Hence, the decision remains the same, planning to accept the escalation and invalidate the issue.

**Comment by ZdravkoHr** [comment]
It actually says 

> On the backend, longer lock periods will be reserved

And that's the only info we got on the lock periods. We knew the team planned to use longer periods (they may be or may be not multiple of `defaultRelockTime`). I don't think an example given by the sponsors in discord should be considered as the only possible values that will be used.

**Comment by notN000B** [comment]
@WangSecurity 

>  I believe it would be fair to invalidate this report because this issue wouldn't cause any problems.  I don't say the report is invalid, but rather low/info

Wow, someone had the courage to say it. Paying more penalty isn't an issue, right?

>it was known information that the only lock period would be 30 days.

lemme correct you since you jumped in chat recently
1. `lock period >= default relock time`
2. default relock time is 30 days
3. This issue is all about when ` lock period % default relock time !=0 `

Before invalidating, please link the source/docs that helped you understand that `lock time will be only a multiple of default lock time`. I'm reading the same thing but unable to understand the conclusions you're drawing

Available Information

1. Test files : These test whether the code behaves properly if the lock period is 30, 60, or 360 days. They don't show that the lock time will only be a multiple of the default relock time
2. A sponsor's text in the contest channel: The sponsor tries to explain what it may look like, but there's no information that the lock time will only be a multiple of the relock time
3. What if this issue arises for 90 days? {Assume for a sec }Would you treat it the same way, by saying it isn't mentioned that a 90-day lock time will be used, and as the sponsor now knows about the 90-day issue, they won't configure a 90-day lock period? Does that make any sense?


This was just a coincidence that all the used lock time was multiple of relock time.

**Comment by WangSecurity** [comment]
Thank you for that message, I'll try to respond to your every point, please tell me if I missed anything.

> Before invalidating, please link the source/docs that helped you understand that lock time will be only a multiple of the default lock time. I'm reading the same thing but unable to understand the conclusions you're drawing

Yes, no resource says the lock time will only be a multiple of the default lock time, but can you please link me to the docs/source where it explicitly says that lock time can be any value and not just a multiple of the default lock time? I think there's none and we should stay away from arguments "it's not mentioned anywhere". It can support both sides and doesn't give any specific or objective information.

> Test files: These test whether the code behaves properly if the lock period is 30, 60, or 360 days. They don't show that the lock time will only be a multiple of the default relock time

Doesn't it support the point that only multiples of 30 will be used? And I'm afraid they don't show that lock time can be any value, not just the multiple of the default relock time.

> A sponsor's text in the contest channel: The sponsor tries to explain what it may look like, but there's no information that the lock time will only be a multiple of the relock time

Again, there's no information that the lock time will be any value and not only a multiple of the relock time.

> What if this issue arises for 90 days? {Assume for a sec }Would you treat it the same way, by saying it isn't mentioned that a 90-day lock time will be used, and as the sponsor now knows about the 90-day issue, they won't configure a 90-day lock period? Does that make any sense?

Before I answer, I'll explain my main argument, and why I believe my decision was correct. Firstly, as you can see, all the arguments you used above can also support my side. Hence, let's use more specific and objective arguments, rather than the ones that make the situation only more controversial. Secondly, as we all know, the protocol's admins for this protocol are TRUSTED, and for locks, there is a configuration that would **not** cause an issue. Hence, we should assume that the TRUSTED admins will use **only** the values that would not cause any problems. The argument that the sponsor didn't know about this issue with other values is not valid, cause it was known **only after** the contest had ended. During the contest, any examples of the lock time that were given for the lock time were always 30 or multiples of it (in the tests, in the chats, even in the readme to the code). Therefore, the correct decision here is to assume that the TRUSTED admin would only use values that wouldn't cause any issues. Hope for your understanding.

The decision remains the same, planning to accept the escalation and invalidate the report.

**Comment by YD-Lee** [comment]
@WangSecurity I cannot agree with your point of view.

1. Indeed, there is no explicit mention of whether `lockTimes` is a multiple of `defaultRelockTime`. But isn't Watson's job to look for issues from all possibilities? Neither in the documentation, test cases, nor Discord does it state that `lockTimes` must be a multiple of `defaultRelockTime` and that `defaultRelockTime` will not change. We should not generalize it from isolated cases. Therefore, the possibility of a non-multiple exists, which means this issue is possible.

2. Admins are trusted, and they are expected to configure contracts in the correct way so as not to cause any problems. However, correct configurations do not mean "theoretically correct" ones, but "practically correct" ones (i.e. the ones that admins believe are correct). How can a person avoid a problem if he is not aware of it? Besides, the sponsors also admit that it is lucky that the `lockTimes` they chose happen to be a multiple of `defaultRelockTime`. Can we ensure that `defaultRelockTime` set by admin next time will still be able to divide the `lockTimes`?

**Comment by WangSecurity** [comment]
@YD-Lee thank you for these points, but they were already brought up by other Watsons in the discussion above. I've taken them into consideration and explained above why this issue has to be deemed invalid. I would like to ask you to not repeat the same information that has already been addressed above and taken into consideration.

The decision remains the same, planning to accept the escalation and invalidate the report.

**Comment by YD-Lee** [comment]
Besides, I noticed that in another audit, @nevillehuang  confirmed a similiar [issue](https://github.com/sherlock-audit/2024-05-beefy-cowcentrated-liquidity-manager-judging/issues/71) as valid. That issue arises when the output token is one of the lpTokens, which are all set by admin. How should this be explained?

**Comment by WangSecurity** [comment]
Firstly, historical decisions are not sources of truth and the decisions on one contest don't affect decisions on the others. Secondly, I believe the comment [here](https://github.com/sherlock-audit/2024-05-beefy-cowcentrated-liquidity-manager-judging/issues/71#issuecomment-2153449947) explains why it's not a mistake. 

 The decision remains the same, planning to accept the escalation and invalidate the report.

**Comment by YD-Lee** [comment]
> @YD-Lee thank you for these points, but they were already brought up by other Watsons in the discussion above. I've taken them into consideration and explained above why this issue has to be deemed invalid. I would like to ask you to not repeat the same information that has already been addressed above and taken into consideration.
> 
> The decision remains the same, planning to accept the escalation and invalidate the report.

@WangSecurity  Thanks for your reply. The reasons above cannot persuade me, but I respect your decision.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [SUPERMAN-I4G](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/256/#issuecomment-2141758559): accepted

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
