### ISSUE TITLE
imsrybr0 - Users can use their expiring locks to increase their rewards right before a rewards notification

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-gamma-staking-judging#296]
imsrybr0

medium

# Users can use their expiring locks to increase their rewards right before a rewards notification

## Summary
Users can front-run rewards notification and withdraw earlier than expected as long as they have other locks that are close to expire.

https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L349-L371

## Vulnerability Detail
* Bob stakes an amount X for the minimum duration.
* Bob waits for an interesting variation in rewards that happens close to the end of his lock cycle
* Bob then skates the same amount X again right before rewards notifications (can be triggered by him) and initiates a late exit for his first lock.
* Bob withdraws his first lock amount as soon as possible (could be as low as 1 second)

## Impact
Increase rewards at the expense of other stakers while being able to withdraw earlier than expected. 

## Code Snippet
```solidity
    function testRewards() public {
        vm.startPrank(user1);
        lock.stake(1 ether, user1, 0);

        vm.startPrank(user2);
        lock.stake(1 ether, user2, 0);

        skip(lockPeriod[0] - 1);

        assertEq(lock.calcRemainUnlockPeriod(lockList.getLock(user1, 0)), 1); // Remaining lock time should be 1 second

        vm.startPrank(deployer);
        _rewardToken.mint(address(lock), 1 ether);

        vm.startPrank(user1);
        lock.stake(1 ether, user1, 2);

        lock.notifyUnseenReward(rewardTokens);

        lock.getAllRewards();

        lock.exitLateById(0);

        skip(1);

        lock.withdrawUnlockedTokenById(0);
    }
```

## Tool used
Manual Review

## Recommendation
Not sure how to mitigate this without having a global per user cooldown on late exists / withdrawals.

**Comment by santipu03** [comment]
My understanding is that all MEV issues are known risks, as the README clearly states.

Still, I believe the scenario described in the report is acceptable because that user will be locked for 30 days with that new lock.

**Comment by imsrybr0** [comment]
Yes, the new lock will have a 30 days locking period but effectively the user would have increased his rewards by locking for 1 second.

**Comment by imsrybr0** [comment]
Escalate

> Any MEV issues related to sending of the reward tokens are known risks. For example if a user sees a large amount of rewards being sent to the contract in the mempool, it is acceptable that another user frontruns the sending of the rewards by staking ahead of the distribution. This risk is intended to be acceptable due to the fact that we'll keep the lowest lock time at around 30 days.

Front running rewards distribution is acceptable under the assumption that the newly deposited funds are locked for 30 days.

This is true when the user has no prior locks and deposits for the first time just to get rewards. The counterpart being that his funds are locked for the next 30 days. 

However, when a user has prior locks, he can leverage those locks to increase his rewards without locking new funds for the expected 30 days period. In this scenario, the user will only have to lock for as low as 1 second, essentially bypassing the expected 30 days lock period counterpart.

From the user's perspective, not much changes as he only had two options for his previous locks initially :
* Either exit and forego future rewards
* Keep his locks to get future rewards
 
Other users on the other hand get less rewards.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> > Any MEV issues related to sending of the reward tokens are known risks. For example if a user sees a large amount of rewards being sent to the contract in the mempool, it is acceptable that another user frontruns the sending of the rewards by staking ahead of the distribution. This risk is intended to be acceptable due to the fact that we'll keep the lowest lock time at around 30 days.
> 
> Front running rewards distribution is acceptable under the assumption that the newly deposited funds are locked for 30 days.
> 
> This is true when the user has no prior locks and deposits for the first time just to get rewards. The counterpart being that his funds are locked for the next 30 days. 
> 
> However, when a user has prior locks, he can leverage those locks to increase his rewards without locking new funds for the expected 30 days period. In this scenario, the user will only have to lock for as low as 1 second, essentially bypassing the expected 30 days lock period counterpart.
> 
> From the user's perspective, not much changes as he only had two options for his previous locks initially :
> * Either exit and forego future rewards
> * Keep his locks to get future rewards
>  
> Other users on the other hand get less rewards.
> 
> 
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by santipu03** [comment]
According to the README, front-running is not possible due to the use of MEV-blockers.

> It is acceptable for users to try and front-run the sending of the rewards and staking before hand. Typically this will be taken care of via MEV-blockers, but even if not, it would still be considered acceptable given that the nature of the contract prevents deposits and withdraws in the same transaction.

The expression "_even if not_", means that this isn't an issue even if MEV-blockers are not used, but it's already clear that those will be used in the previous phrase.  With MEV-blockers, no front-running is possible, making this issue invalid.

**Comment by imsrybr0** [comment]
Hi @santipu03,

I understand your concern but since anyone can call notifyUnseenReward, the MEV blockers solution would have to cover both it and the tokens being sent to the contract transactions which contradicts the following code comment :

```solidity
    /// @notice Checks for and registers any rewards sent to the contract that have not yet been accounted for.
    /// @dev This function is used to update the contract's state with rewards received but not yet recorded, 
    ///      for example, tokens sent directly to the contract's address 
    ///      It should be called periodically, ideally every 24 hours, to ensure all external rewards are captured.
    /// @param token The address of the reward token to check for new, unseen rewards.
    function _notifyUnseenReward(address token) internal {
```

Hopefully this clears it up a little more.

**Comment by santipu03** [comment]
I don't quite understand your comment, could you rephrase it, please?

**Comment by imsrybr0** [comment]
Sorry about that, my bad.

The rewards distribution flow is :
1) Reward tokens are sent to the Lock contract
2) notifyUnseenReward is called to distribute rewards for each reward token.

Since notifyUnseenReward is not permissionned, the MEV blockers solution is only viable if it covers both steps of the rewards distribution flow at the same time (.i.e including both in the same bundle).

However, the following comment implies that both steps are done separately :
> It should be called periodically, ideally every 24 hours, to ensure all external rewards are captured

Please let me know if it is still not clear, thank you

**Comment by santipu03** [comment]
> Since notifyUnseenReward is not permissionned, the MEV blockers solution is only viable if it covers both steps of the rewards distribution flow at the same time (.i.e including both in the same bundle).

When the sponsors specify that they will use MEV-blockers to send rewards, I assume that they will bundle both transactions in the same block. It makes no sense to not do it like that because it would defeat the purpose of using MEV-blockers. 

> It should be called periodically, ideally every 24 hours, to ensure all external rewards are captured

I believe those "external rewards" are the rewards sent by external actors (not the admins) for unknown purposes. Because no other actors than the admins are incentivized to distribute rewards to the contract, I don't believe that anyone just sends rewards giving out free money. If some random people want to send rewards to the `Lock` contract and they don't use MEV-blockers, they may be frontrunned, but I don't believe this scenario is realistic because it's based on a random donation. 

As specified on the README, all rewards distribution coming from the protocol will use MEV-blockers, making frontrunning impossible.

**Comment by imsrybr0** [comment]
Understood, but I think those assumptions are not necessarily true for the following reasons.

The README tackles the front running issues in two separate sections :

> The reward tokens will be sent periodically to the staking contract and function notifyUnseenRewards() will be called.
It is acceptable for users to try and front-run the sending of the rewards and staking before hand. Typically this will be taken care of via MEV-blockers, but even if not, it would still be considered acceptable given that the nature of the contract prevents deposits and withdraws in the same transaction. 

> Any MEV issues related to sending of the reward tokens are known risks. For example if a user sees a large amount of rewards being sent to the contract in the mempool, it is acceptable that another user frontruns the sending of the rewards by staking ahead of the distribution. This risk is intended to be acceptable due to the fact that we'll keep the lowest lock time at around 30 days.

* In the first part, MEV blockers mentioned as the solution to front running rewards distribution. But right before it, it is said that the reward will be sent periodically to the staking contract and the function notifyUnseenRewards will be called afterwards which agrees with what the code comment says (.i.e rewards sent periodically to the Lock contract and distribution happening periodically to capture all rewards)
* In the second part, it says that the risk is acceptable as long as the lock period for the newly deposited funds is 30 days, which implies that front running is possible.

**Comment by santipu03** [comment]
I agree that the README is kind of unclear regarding frontrunning, but I believe the statement that they use MEV-blockers invalidates all frontrunning issues.

**Comment by imsrybr0** [comment]
Agreed, there are some discrepancies in the README.

My understanding is that the sponsor could use MEV blockers for reward notifications and even if they didn't, they are confident that front running wouldn't be an issue because of the 30 days lock period.

Furthermore, periodic distribution and notification mean that both are predictable to some extent.

Please also consider the fact that immediately front running the reward notification is the best scenario for the user. Even if that is prevented, it is possible use this as a way to increase rewards without locking for the full 30 days period.

Those are the reasons why I filed this report in the first place and why I believe it's valid.

**Comment by santipu03** [comment]
Suppose we discard the frontrunning scenario and the user only stakes and withdraws timing those actions to get more rewards. In that case, I believe it's an expected behavior and falls under a design decision issue.

**Comment by imsrybr0** [comment]
In that case, I would be more inclined to think it's an unforseen behavior than to think that bypassing a locking contract minimum locking period to receive rewards is by design.

**Comment by nevillehuang** [comment]
I agree with lead judge judgement, this is basically describing the following known scenario

> The reward tokens will be sent periodically to the staking contract and function notifyUnseenRewards() will be called.

> It is acceptable for users to try and front-run the sending of the rewards and staking before hand. Typically this will be taken care of via MEV-blockers, but even if not, it would still be considered acceptable given that the nature of the contract prevents deposits and withdraws in the same transaction.

Planning to reject escalation and leave issue as it is.

**Comment by imsrybr0** [comment]
What I believe is a known issue is the front running rewards distribution with no pre existing locks, as the funds will be locked for the expected 30 days period even if MEV blockers are not used. That is perfectly acceptable as later stated in another section of the README.

I tried my best to outline the issue that arises in the scenario where the user has existing locks which essentially allows him to bypass the 30 days locking period limitation.

It's up to you however to decide whether or not that is an acceptable risk for a locking contract that enforces penalties on early exits to allow users to increase their rewards without locking funds for the full expected period.

**Comment by nevillehuang** [comment]
Still planning to reject the escalation based on comments [here](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/296#issuecomment-2143114276). The following scenario is pointing to MEV.

> Bob then skates the same amount X again right before rewards notifications (can be triggered by him) and initiates a late exit for his first lock.

**Comment by imsrybr0** [comment]
> The following scenario is pointing to MEV

It also includes the predictability of periodic reward distribution and notification scenario.

As watsons, we are asked to describe the worst case scenario, which in this case is front running (not necessarily is the same block) right before  a reward notification and very close to the end of an existing lock current cycle.

To summarize my arguments :
* From the full README, the sponsor is confident that, even if MEV blockers are not used, front running rewards notification is not an issue as the funds will be locked for the full 30 days period.
* That is indeed an acceptable risk when the user has no existing locks since the new funds will be locked for the expected 30 days period.
* When a user has an existing lock, he can create another lock to increase his next rewards and exit late on his first lock after the notification happens.
* This allows the user to increase his rewards by only locking funds for the time remaining in his first lock current cycle.
* MEV is not a prerequisite for this to be possible, it's just the best scenario for the user. 
* As long as the time remaining in the first lock current cycle is less than the minimum 30 days locking period, this allows the user to increase his rewards without locking new funds for the full expected 30 days period.
* It doesn't make sense for a locking contract to enforce penalties on early exits on one hand and still allow users to increase their rewards without locking for the full period on the other hand.

**Comment by nevillehuang** [comment]
@imsrybr0 The escalation period is not to supplement what is the intended meaning of your original submission. Based on reading your original submission, you are highlighting an MEV scenario so I believe my judgement still stands.

> Users can front-run rewards notification and withdraw earlier than expected as long as they have other locks that are close to expire.

**Comment by imsrybr0** [comment]
I'm not supplementing my submission in any way. I just feel obligated to answer each different new concern as it is raised.

For instance here, you're mentioning that the use of the "front-running" word in my description automatically makes this about MEV and I argue that:
* Front running just means sending a transaction before another one. In the MEV context, that transaction is in the same block. Outside that context it can be any time before.
* What word would you have used to describe sending a transaction before another one?
* What about the title of the submission, the vulnerability details?

**Comment by nevillehuang** [comment]
@imsrybr0 I suggest you to carefully read what is the acceptable known risk again, especially `It is acceptable for users to try and front-run the sending of the rewards and staking before hand`. Still planning to reject escalation and leave issue as it is.

> It is acceptable for users to try and front-run the sending of the rewards and staking before hand. Typically this will be taken care of via MEV-blockers, but even if not, it would still be considered acceptable given that the nature of the contract prevents deposits and withdraws in the same transaction.

**Comment by imsrybr0** [comment]
Hi @nevillehuang,

Trust me, I did. I wouldn't have filed this report and wouldn't have escalated it if I was convinced this is a known issue.

Those are the README sections that lead me to believe otherwise :

> ... Typically this will be taken care of via MEV-blockers, **but even if not**, it would still be considered acceptable given that the nature of the contract prevents deposits and withdraws in the same transaction.

> ... This risk is intended to be acceptable due to the fact that we'll keep the lowest lock time at around 30 days.

> The reward tokens will be sent periodically to the staking contract and function notifyUnseenRewards() will be called.

Based on this and my understanding of the code base (penalties on early exits, comments about periodic notification), it seemed to me that the sponsor was unaware of this issue and was talking about first time lockers which justified their confidence in the locking period being a good enough measure to even make MEV blockers usage optional.

Whether I agree with it or not, I'm ok with whatever decision you make and will defer to your judging and auditing expertise.

Thanks

**Comment by WangSecurity** [comment]
Still, under the contest's README, front-running will not be possible for that protocol due to MEV-blockers. Even if they don't work, it's an acceptable risk as per README. Hence, the decision remains the same, reject the escalation and leave the issue as it is.

**Comment by imsrybr0** [comment]
Hi @WangSecurity, front running the rewards notification **transaction** will not possible in the same block **if** MEV blockers are used but you can still front run the reward notification in prior blocks especially if it happens periodically at predefined times.

**Comment by WangSecurity** [comment]
And as the README says, even if it's not taken care of via MEV-blockers, it's an acceptable behaviour.

The decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by imsrybr0** [comment]
Yes, and as the README states, it's only acceptable in that case if the minimum 30 days lock period constraint holds.

**Comment by WangSecurity** [comment]
And based on the README, it’s explicitly stated that the minimum will indeed be 30 days. Otherwise, it would be an admin error.

The decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by imsrybr0** [comment]
Yes, the minimum locking period is 30 days. No admin errors are assumed here.

What I tried to show in this issue, is that, that minimum locking period constraint doesn't necessarily hold when a user has existing locks.

![image](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/assets/103459962/c8b076f9-c170-4d04-91f0-dc1c2c1d6143)

**Comment by WangSecurity** [comment]
@imsrybr0 excuse me, but if the user has an existing lock, and they decide to lock more, then still they will have to lock for at least 30 days, no? What do you mean by “minimum locking period doesn’t hold”? Isn’t it just how the protocol works? Excuse me if I’m missing anything here.

**Comment by imsrybr0** [comment]
No no, you're not missing anything, that's indeed how it works. If you look at every lock individually,  the minimum 30 days locking period holds.

Not sure if it makes sense but the way I reflect about this is "How long is an additional 1 ether locked for increased rewards ?" as opposed to "How long is each 1 ether locked for increased rewards ?"

**Comment by WangSecurity** [comment]
Then, as I understand, it's how the protocol works. The user who has locked 1 ETH twice, will get more than the user who has locked 1 ETH only once. And as you say yourself, your issue only holds if the minimum lock period of 30 days doesn't hold, but based on the README, we have to assume it will always hold. 

Hence, the decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by imsrybr0** [comment]
Not exactly, the user who locked 1 ether twice only locked one of those for T Lock 1 + 30 days - T Lock 2.

**Comment by WangSecurity** [comment]
Could you please rephrase, I'm not sure I understand what you mean here.

**Comment by imsrybr0** [comment]
Sure, sorry for the confusion:

So, initially, the user has only three options for his lock :

* Early exit, pay penalties and get his 1 ether immediately while also foregoing future rewards. 
* Late exit and wait for the end of cooldown period (remaining time in the current cycle of the lock) while also foregoing future rewards.
* Keeps his 1 ether locked, going through future cycles (30 days each) and earning future rewards.

Since the rewards are based on the amount of ETH locked by the user at the time of the notification, if the user chooses the third option, they can use this to lock an additional 1 ether to increase their rewards.

From the user perspective, besides getting increased rewards, nothing changes as they will still have 1 ether locked at end.

So despite the fact that each lock individually is lasting for 30 days, the additional 1 ether will effectively only be locked for the time between the start of the second lock and the end of the first lock due to the overlap between the locks.

In summary, there is a difference between **"How long does a lock last ? => 30 days"** and **"How long are funds locked ? => Can be less than 30 days"**.

**Comment by WangSecurity** [comment]
@imsrybr0 I assume this can be done without front-running?

**Comment by imsrybr0** [comment]
No, the user always has to front run the reward notification (either in the same block by monitoring the mempool when MEV blockers are not used or in prior blocks by predicting rewards notification time if it's done periodically at predefined times), otherwise their rewards will not be increased.

**Comment by WangSecurity** [comment]
Even with this great explanation (and genuinely thank you for that) it’s still an acceptable risk of front-running based on the contest’s QA.

The decision remains the same, reject the escalation and leave the issue as it is.

**Comment by imsrybr0** [comment]
I just tried my best to explain why I didn't think this is a known risk 🙏

As I said earlier, I'll respect the decision made here regardless of whether I agree with or not.

Thanks a lot @santipu03, @nevillehuang, @WangSecurity for reviewing this, I appreciate your effort and time 👍

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [imsrybr0](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/296/#issuecomment-2139060655): rejected
