### ISSUE TITLE
0x77 - User can reclaim more rewards

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-gamma-staking-judging#320]
0x77

high

# User can reclaim more rewards

## Summary
User can reclaim more rewards by calling restakeAfterLateExit after callingwithdrawAllUnlockedToken function

## Vulnerability Detail
Lets suppose a scenario
1.  user has staked amount
2. completed the lock period 
3. called callingwithdrawAllUnlockedToken  function and claim all the tokens including reward
4. then user called restakeAfterLateExit  and without depositing or staking any further amount , he can again reclaim the same balance until contract run out of tokens

## Impact
High 

## Code Snippet
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L294
## Tool used
Manual
Manual Review

## Recommendation
isRelock is not sufficient 
checks need to be applied in restaking that if the user has withdrawn

**Comment by MrValioBg** [comment]
About step 2 - "completing lock period," the modulo in calcRemainUnlockPeriod() ensures that if we have lockperiod = 30 and timeSinceLock = 31, the function will return 29 days left. 
So, the withdrawAllUnlockedToken function cannot be called without the exitLateById being called first.

After calling withdrawAllUnlockedToken, you cannot call restakeAfterLateExit for the same lockedId, as in both withdraw functions `locklist.removeFromList()` is called, so the issue is invalid.
