### ISSUE TITLE
mwendwa - _updateReward is not updated in the _getReward function

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-gamma-staking-judging#321]
mwendwa

medium

# _updateReward is not updated in the _getReward function

## Summary
In the function ```_getReward``` the ```_updateReward``` is called before the reward is transferred and not called after it is transferred.
## Vulnerability Detail
This issue mentioned above does not update the reward given so a user could call ```_getReward``` multiple times to get more rewards than he should get
POC
add this lines in withdraw.t.sol after the last assertEq

```solidity
vm.prank(deployer);
        _rewardToken.transfer(address(lock), 300e18);
        vm.prank(deployer);
        lock.notifyUnseenReward(rewardTokens);
        vm.prank(user3);
        lock.getAllRewards();
        vm.prank(deployer);
        _rewardToken.transfer(address(lock), 300e18);
        vm.prank(user3);
        lock.getAllRewards();
```
## Impact
The protocol can loose all available rewards to one user.
## Code Snippet
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L538-L559
## Tool used

Manual Review

## Recommendation
CALL ```_updateReward``` after sending the rewards

**Comment by MrValioBg** [comment]
_updateReward is called before getReward, so the rewards and rewardDebt mapping could be updated.

Calling updateRewards before _getRewards ensures that Rewards are up to date as the rewards mapping is updated. It tracks the reward amount to waiting be claimed.

If there was no update on the cumulatedRewards via notifyUnseenReward between the two reward calls, there would be no change in the rewards mapping, thus no extra rewards would be claimed.

This issue seems invalid, also, the POC does not include any assertions.
