### ISSUE TITLE
CryptoSan - Users can call multiple times `exitLateById` for the same lock

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-gamma-staking-judging#45]
CryptoSan

medium

# Users can call multiple times `exitLateById` for the same lock

## Summary

Users can call multiple times `exitLateById` for the same lock

## Vulnerability Detail

Users are able to call `exitLateById` multiple times for the same lock. Let's say I've two locks first, first lock equal to 100 tokens, and the second one 200 tokens. By mistake I'll `exitLateById` for the first lock twice, those transactions will pass. Then if I try to exit from the second lock the transaction will revert because there is not enough value in the `bal.lockedWithMultiplier` variable. The result is that funds in the second lock, are stuck and cannot be exited. This also breaks protocol invariants because `lockedSupplyWithMultiplier`, and `lockedSupply` no longer track the real amount locked funds in the protocol.

In the `RestakeAfterLateExit.t` add the following test

```solidity
function test_multiple_exit_late_for_the_same_lock() public {
    vm.startPrank(user1);
    lock.stake(100e18, user1, 0); // first stake, lockId 0
    lock.stake(200e18, user1, 0); // second stake, lockId 1

    uint256 firstStakeLockId = 0;

    // we are able to exit late twice for the same lock
    lock.exitLateById(firstStakeLockId);
    lock.exitLateById(firstStakeLockId);

    uint256 secondStakeLockId = 1;

    // because we exited late twice for the same lock
    // exiting late for the second lock revers because of the underflow
    // for bal.lockedWithMultiplier it tries to subtract 200e18 from 100e18
    vm.expectRevert();
    lock.exitLateById(secondStakeLockId);
   
}
```

## Impact

The user's lock funds are stuck in the contract. Protocol invariants are broken.

## Code Snippet

https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L349

## Tool used

Manual Review

## Recommendation

Don't allow to call `exitLateById` for the same lock multiple times

```diff
function exitLateById(uint256 id) external {
        _updateReward(msg.sender); // Updates any pending rewards for the caller before proceeding.

        LockedBalance memory lockedBalance = locklist.getLockById(msg.sender, id); // Retrieves the lock details from the lock list as a storage reference to modify.
+       if(lockedBalance.exitedLate) revert InvalidLockId(); // Ensures the lock has not already exited

        // Calculate and set the new unlock time based on the remaining cooldown period.
        uint256 coolDownSecs = calcRemainUnlockPeriod(lockedBalance);
        locklist.updateUnlockTime(msg.sender, id, block.timestamp + coolDownSecs);

        // Reduce the locked supply and the user's locked balance with and without multiplier.
        uint256 multiplierBalance = lockedBalance.amount * lockedBalance.multiplier;
        lockedSupplyWithMultiplier -= multiplierBalance;
        lockedSupply -= lockedBalance.amount;
        Balances storage bal = balances[msg.sender];
        bal.lockedWithMultiplier -= multiplierBalance;
        bal.locked -= lockedBalance.amount;

        locklist.setExitedLateToTrue(msg.sender, id);

        _updateRewardDebt(msg.sender); // Recalculates reward debt after changing the locked balance.

        emit ExitLateById(id, msg.sender, lockedBalance.amount); // Emits an event logging the details of the late exit.
    }
```

**Comment by guhu95** [comment]
@santipu03 

1. For this to be a user mistake it must be explicitly or implicitly known to be a mistake (have bad consequences). If the user cannot possibly know this can cause a loss - it cannot be considered their mistake. In true "user mistake" cases the mistake can be expected: like transferring to wrong address, or renouncing ownership. Or it can be unexpected but documented and warned due to non-obvious side-effects. But in this case it's neither expected nor documented. Even the devs weren't aware - which is why they fixed it now.

2. In addition to this, there are scenarios where users will likely call this (since they cannot know the negative effects). I describe some scenarios in https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/8, and pkqs describes another one in https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/204.

3. Finally, https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/65 is valid, and will directly cause users to submit multiple successive calls to `exitLateById` if the first wasn't confirmed yet to prevent re-lock for an extended duration. If it isn't a user mistake to submit a transaction "too late" (which very obviously will be included at unknown time), it definitely isn't a user mistake to try to submit again. If the user reloads and clicks the UI button again, another tx be created, and both will succeed.

No abundance of caution can help the users here - it's a clear bug that causes a completely unexpected loss without the user possibly knowing it in advance, and with many scenarios that can trigger it.

**Comment by santipu03** [comment]
Before invalidating the issue, we've already analyzed each scenario described in those reports by several judges and myself, and the final decision was that the root cause was a user mistake.

**Comment by guhu95** [comment]
@santipu03 I appreciate the additional context about multiple judges, but it didn't explain the reasoning that led to the decision. 

Specifically, how can this be considered a user mistake if the user cannot know it is a mistake?

**Comment by aslanbekaibimov** [comment]
Escalate

Agree with @guhu95 's points

https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/45#issuecomment-2138501772

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Agree with @guhu95 's points
> 
> https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/45#issuecomment-2138501772

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by santipu03** [comment]
A user can make a mistake unknowingly. In fact, all user mistakes are made unknowingly at the execution time, if not, the user won't be committing that mistake at all. 

The function `exitLateById` is not designed to be called twice for the same lock, it doesn't make sense. For this reason, all users calling that function twice for the same lock is considered a user mistake.

**Comment by guhu95** [comment]
> A user can make a mistake unknowingly. In fact, all user mistakes are made unknowingly at the execution time, if not, the user won't be committing that mistake at all.

@santipu03 I think you've misunderstood my point, and so your response is kinda unrelated. A mistake is an action a careful user will try to avoid. In this case the user has no reason to avoid this action, and instead there are scenarios (like congestion or RPC latency) in which even the careful user is likely to trigger the issue.

It's like if pushing an elevator button twice, instead of nothing happening, the elevator would explode with the user. If the button light is too slow, or too dim, even a careful user may press it again. Thus it is not a user mistake, but a critical flaw in the [finite state machine](https://en.wikipedia.org/wiki/Finite-state_machine) of the elevator.

**Comment by lizhming** [comment]
> The function exitLateById is not designed to be called twice for the same lock, it doesn't make sense. For this reason, all users calling that function twice for the same lock is considered a user mistake.

@santipu03 Where is the information stating that the exitLateById function is not designed to be called twice for the same lock?

**Comment by santipu03** [comment]
Even though it's not explicitly stated that the function `exitLateById` should only be called once, it's pretty obvious to know by just reading the Natspec:
```solidity
    /// @notice Allows a user to execute a late exit from a lock by specifying the lock ID, updating unlock times and reducing locked balances.
    /// @dev This function adjusts the unlock time based on the remaining cooldown period, updates the locked balances, flags the lock as exited late, and logs the exit.
    /// @param id The unique identifier of the lock from which the user wishes to exit late.
    function exitLateById(uint256 id) external {
```

@guhu95 Our misunderstanding arises from differing interpretations of what constitutes a _"user mistake"_. While I don't entirely disagree with your definition, based on my experience with Sherlock and after consulting it with other judges, I classified this issue as invalid. In my view, calling a function twice that is intended to be called only once qualifies as a user mistake.

**Comment by nevillehuang** [comment]
I personally believe this issue should remain low severity.

1. I don't think this is relevant to the discussion. Users are presumed to understand how to logically use the functions, in this case exits are supposed to be called once.

2. All the scenarios you highlighted are not relevant based on the argument above except possibly the gas congestion scenario. Even in that scenario, users are responsible to be providing sufficient gas for the transaction and wait for finality

Will consult sherlock internal team on this issue.

CC: @WangSecurity

**Comment by guhu95** [comment]
@nevillehuang 

> ... except possibly the gas congestion scenario. Even in that scenario, users are responsible to be providing sufficient gas for the transaction and wait for finality

Gas prices vary and spike unexpectedly, and this call is highly time-sensitive because of the risks of penalty / relock (see #65 for example). This prevents users from waiting out a gas spike.

Another scenario is RPC latency / brown-out, which are highly common with L2s in times of load. A user may submit the tx to an RPC, and due to the risk of penalty or relocking, either try to submit again, or switch to another RPC and submit the same tx again. Because there is no known risk for submitting twice (similar to "pressing the elevator button twice"), even careful users are likely to do it.

On another note, I can't imagine an audit report (either solo or firm) that would put this issue under low. It would be highly negligent, since there's a severe bug, and no user will consider this loss "their fault". Of course Sherlock has its own rules, but allowing this to be a low (invalid in Sherlock), causes the report to omit the most severe actual bug in this audit.

**Comment by ydspa** [comment]
@nevillehuang Plz take consideration of the scenario of network congestion, it's reasonable for users to retry ````unlocking```` their funds.
> 
> > ... except possibly the gas congestion scenario. Even in that scenario, users are responsible to be providing sufficient gas for the transaction and wait for finality
> 
> Gas prices vary and spike unexpectedly, and this call is highly time-sensitive because of the risks of penalty / relock (see #65 for example). This prevents users from waiting out a gas spike.
> 
> Another scenario is RPC latency / brown-out, which are highly common with L2s in times of load. A user may submit the tx to an RPC, and due to the risk of penalty or relocking, either try to submit again, or switch to another RPC and submit the same tx again. Because there is no known risk for submitting twice (similar to "pressing the elevator button twice"), even careful users are likely to do it.
> 
> On another note, I can't imagine an audit report (either solo or firm) that would put this issue under low. It would be highly negligent, since there's a severe bug, and no user will consider this loss "their fault". Of course Sherlock has its own rules, but allowing this to be a low (invalid in Sherlock), causes the report to omit the most severe actual bug in this audit.

**Comment by nevillehuang** [comment]
@ydspa @guhu95 Yes will reconsider, I see the argument for gas price spikes often and believe we need a discussion revolving this to set precedence for future issues. Will consult with sherlocks judging team.

Although I must say, the function logic is correct, even if we did not allow exiting twice, the positions will still relock, there is no loss of funds since users would still retain their multipliers and infact would possibly get more rewards. So the fact here is users should understand that they can only exit late once and then wait for finality.

**Comment by guhu95** [comment]
@nevillehuang 

> Although I must say, the function logic is correct, ... there is no loss of funds since users would still retain their multipliers and infact would possibly get more rewards. So the fact here is users should understand that they can only exit late once and then wait for finality.

I'm not sure if maybe you've misunderstood the impact of a second call. The user's other locks will be irrecoverably lost due incorrect balance update - both staked funds (principal) and future rewards (yield). Maybe it's a bit clearer in my dup's description of the issue - #8.

**Comment by nevillehuang** [comment]
@guhu95 I understand the impact and will reconsider severity.

**Comment by nevillehuang** [comment]
Based on discussions with sherlock judge, it is concluded that users should never call `exitLateById` twice based on the intended use case, and if they do it will be considered a mistake, so it falls under the following category:

> User input validation: User input validation to prevent user mistakes is not considered a valid issue.

The same stance on validity of issue will be taken [here](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/45#issuecomment-2143112696)

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [aslanbekaibimov](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/45/#issuecomment-2141607376): rejected

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
