### ISSUE TITLE
h2134 - User may create a lock with an unexpected lock type

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-gamma-staking-judging#69]
h2134

medium

# User may create a lock with an unexpected lock type

## Summary
User may create a lock with an unexpected lock type.

## Vulnerability Detail
When a user calls [stake(...)](https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L245-L249) function to create a lock, `typeIndex` is passed to specify the lock type, and different lock types have different multiplier and lock period.
```solidity
        uint256 multiplier = rewardMultipliers[typeIndex];
        ...

        locklist.addToList(
            onBehalfOf, 
            LockedBalance({
                lockId: 0, // This will be set inside the addToList function
                amount: amount,
                unlockTime: 0, 
                multiplier: multiplier,
                lockTime: block.timestamp,
                lockPeriod: lockPeriod[typeIndex],
                exitedLate: false
            })
```
Lock type can also be changed by the owner through [setLockTypeInfo(...)](https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L128-L131) function. For example, the lock types are:
```diff
0:  10 days
1:  30 days

0:  1x multiplier
1:  2x multiplier
```
The owner submit an transaction to change to:
```diff
0:  10 days
1:  60 days

0:  1x multiplier
1:  1x multiplier
```
Before the transaction is executed, a user calls **stake(...)** function with `typeIndex` is 1, they expect to create a lock for 30 days with 2x multiplier, however, the owner's transaction gets executed first, results in user's funds being locked for 60 days with 1x multiplier.

## Impact
User may lock funds with higher period but lower multiplier than expected.

## Code Snippet
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L245-L249

## Tool used
Manual Review

## Recommendation
Add parameters to **stake(...)** function to ensure user won't create a wrong lock:
```diff
    function _stake(
        uint256 amount,
        address onBehalfOf,
        uint256 typeIndex,
+       uint256 expectedLockPeriod,
+       uint256 expectedMultiplier,
        bool isRelock           
    ) internal whenNotPaused {
        ...

        uint256 multiplier = rewardMultipliers[typeIndex];
+       uint256 lockPeriod = lockPeriod[typeIndex];
+       if (multiplier != expectedMultiplier || lockPeriod != expectedLockPeriod) revert();

        ...
    }
```

**Comment by samuraii77** [comment]
Escalate

Issue should be valid as according to the screenshot sent, the rewards would be initially set as the first example. Then, in the second example, the sponsor explicitly says what the rewards `could look like`. It is clearly uncertain what the exact rewards could change to, thus this issue can definitely arise. If the sponsor said that this is definitely how the lock up periods would look like and it is not subject to a change, then this would not be a valid issue. However, due to the fact that it is expected for the protocol to be changing those values and they have not stated otherwise and the fact that they are uncertain of what these values would exactly change to in the future, this should be a valid medium.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Issue should be valid as according to the screenshot sent, the rewards would be initially set as the first example. Then, in the second example, the sponsor explicitly says what the rewards `could look like`. It is clearly uncertain what the exact rewards could change to, thus this issue can definitely arise. If the sponsor said that this is definitely how the lock up periods would look like and it is not subject to a change, then this would not be a valid issue. However, due to the fact that it is expected for the protocol to be changing those values and they have not stated otherwise and the fact that they are uncertain of what these values would exactly change to in the future, this should be a valid medium.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by santipu03** [comment]
I agree that the sponsor's statement may be up to interpretation. I'll leave the decision to the head of judging.

**Comment by Henrychang26** [comment]
@santipu03 

I believe it is reasonable to assume that the admin will not use `setLockTypeInfo()` recklessly and will always pause the contract before making any updates.

**Comment by samuraii77** [comment]
That is definitely not reasonable to assume, why would you assume that the protocol would pause the contract, set the lock info and unpause it? Furthermore, if that is done in multiple transactions, regular users would be DOSed from using the protocol while if done in 1 transaction, it would not make a difference in the outcome.

**Comment by Henrychang26** [comment]
> That is definitely not reasonable to assume, why would you assume that the protocol would pause the contract, set the lock info and unpause it? Furthermore, if that is done in multiple transactions, regular users would be DOSed from using the protocol while if done in 1 transaction, it would not make a different in the outcome.

Admin is considered trusted, and any configuration changes should be made with caution. The above scenario can be easily avoided by pausing the contract for 5 minutes, to allow all pending transactions to be executed, then `setLockTypeInfo` and unpause to resume normal functionality.

**Comment by samuraii77** [comment]
Still, even if they are trusted, that is not a reasonable series of events and not reasonable to assume the admins would conduct all of those steps. Even if it was reasonable to assume that, this is a very ineffective way to avoid this issue, first of all, it again leads to a DoS for regular users and in fact, this can be extremely detrimental for the users because of issue #65 and how time is really of the essence there. It also stops users from staking based on the initial lock periods and multipliers as the contract will be paused and instead, they will be forced to either stake based on the new periods and multipliers that they might not like or not stake at all.

**Comment by Henrychang26** [comment]
The admin is trusted and expected to not make reckless configuration changes. Whether or not its effective is not relevant to the issue here.
Regarding #65, `exitLateById()` is still available when contract is paused. `earlyExitById()` is not available when paused because the admin might decide to update the penalty rate and `defaultRelockTime`, both of which are used to calculate the penalty amount. If not paused, a similar situation could occur where a user anticipates one penalty amount but receives a different one. This is what led me to believe protocol will pause the contract before making configuration changes. 

>Still, even if they are trusted, that is not a reasonable series of events and not reasonable to assume the admins would conduct all of those steps. Even if it was reasonable to assume that, this is a very ineffective way to avoid this issue, first of all, it again leads to a DoS for regular users and in fact, this can be extremely detrimental for the users because of issue https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/65 and how time is really of the essence there.

The protocol isn't concerned about this
>It also stops users from staking based on the initial lock periods and multipliers as the contract will be paused and instead, they will be forced to either stake based on the new periods and multipliers that they might not like or not stake at all.

**Comment by samuraii77** [comment]
How did you come to the conclusion that the protocol is not concerned about that? Also, if the protocol team had the idea of pausing the protocol before changing the periods and multipliers, they would have mentioned it either in the contest page or would have mentioned it as an argument for why this issue isn't valid.

**Comment by Henrychang26** [comment]
Whether or not users choose to stake is not in the scope of the audit. I have made all my points and will leave it up to the judge.

**Comment by samuraii77** [comment]
That was not my main point. My main point was that you are disallowing users to stake using the current periods and multipliers by pausing the contract at that time. Clearly that is not how the functionality to pause the protocol was intended to be used. I agree that we should leave it up to the judge.

**Comment by nevillehuang** [comment]
I believe this is a trusted admin action, so would be invalid based on the following guidelines. The admin can also simply create a new lock type (with a new corresponding index) while retaining the previous lock type to avoid this. Additionally admins can pause staking before changing lock type

> 3. An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue.

Planning to reject escalation and leave issue as it is.

**Comment by samuraii77** [comment]
Yes, the admins could simply create a new lock type while retaining the previous ones and the issue will not occur. However, what if the admins do not want to keep the previous lock type and just want to change them (in fact, the most likely scenario)? This is effectively making the admins unable to remove lock types that they do not believe are suitable anymore.

Also, I think we should completely stop talking about pausing the contract before changing the lock type as:
* That is clearly not the intended use of the pause functionality in the contract
* It was never mentioned anywhere they would use it like that
* It leads to a DoS for regular users
* Disallows users who want to exit early to do so due to the `whenNotPaused` modifier and as seen in #65, time is really of the essence there
* It is an extremely unreliable way to avoid this issue and in fact, it is not trivial to execute without any consequences

The issue can indeed occur and there is not a way to completely avoid this issue in the current state of the code. If you can provide an actual reliable way to avoid this issue without any consequences, I will agree that this issue deserves a low severity. However, if you can not, I believe that this issue deserves a medium severity.

**Comment by nevillehuang** [comment]
Still planning to reject escalation and leave issue as it is based on comments [here](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/69#issuecomment-2143111420). The rules and pausing mechanism mentioned is sufficient to invalidate the issue.

**Comment by samuraii77** [comment]
I already explained the exact reasons why pausing the contract before updating the lock types is not an actual option, I am not sure why this is even a debate. There is no way to avoid this issue in the current state of the code without creating more problems. I believe this issue should be a Medium however if you can show me a way how this issue can be avoided without creating other issues, then I will agree with you.

**Comment by nevillehuang** [comment]
@samuraii77 I would suggest reading carefully [sherlock rule 5.3, regarding trusted admin actions](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid). 

> 3. An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [samuraii77](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/69/#issuecomment-2137353994): rejected
